/* ===================================================================
   KERATON THEME DATA — Javanese royal (Keraton Surakarta) style
   All theme copy lives here, Bahasa Indonesia FIRST with an English
   secondary reached via  ?lang=en .  Wedding *content* (names, dates,
   story…) stays in ../data.js — never duplicate it here.
   =================================================================== */

window.TEMPLATE = {
  theme: "keraton",

  /* ----- opening greeting (pick the salam that fits your family) ----
     Examples: "Assalamu'alaikum Warahmatullahi Wabarakatuh"
               "Om Swastiastu" · "Salam Sejahtera" · "Shalom"        */
  greeting: {
    salam: "Assalamu'alaikum Warahmatullahi Wabarakatuh",
    body: {
      id: "Dengan memohon rahmat dan ridha Tuhan Yang Maha Esa, kami bermaksud menyelenggarakan pernikahan putra-putri kami. Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir untuk memberikan doa restu.",
      en: "By the grace and blessing of God Almighty, we intend to hold the wedding of our children. It would be an honour and a joy for us if you would kindly attend and give your blessing.",
    },
    closing: {
      id: "Atas kehadiran dan doa restunya, kami mengucapkan terima kasih.",
      en: "For your presence and prayers, we thank you from the bottom of our hearts.",
    },
    closingSalam: "Wassalamu'alaikum Warahmatullahi Wabarakatuh",
  },

  /* ----- optional verse block (set enabled:false to hide) ----------
     Ar-Rum 21 is the Indonesian wedding convention; swap the text for
     a neutral doa or any quote your family prefers.                  */
  verse: {
    enabled: true,
    text: {
      id: "“Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang. Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Allah) bagi kaum yang berpikir.”",
      en: "“And of His signs is that He created for you from yourselves mates that you may find tranquillity in them; and He placed between you affection and mercy. Indeed in that are signs for a people who give thought.”",
    },
    source: "QS. Ar-Rum: 21",
  },

  /* ----- event blocks: akad & resepsi -------------------------------
     time left "" falls back to the shared W.ceremonyTime; the venue
     comes from ../data.js. Adjust the resepsi time to match agenda[]. */
  events: [
    {
      id: "akad",
      title: { id: "Akad Nikah", en: "Akad Ceremony" },
      time: "", // "" → W.ceremonyTime
      note: {
        id: "Akad nikah bersifat khidmat; kami mohon kehadiran tepat waktu.",
        en: "The akad is a solemn ceremony; we kindly ask you to arrive on time.",
      },
    },
    {
      id: "resepsi",
      title: { id: "Resepsi", en: "Reception" },
      time: "18.30 WIB",
      note: {
        id: "Ramah tamah bersama keluarga sambil menikmati hidangan dan hiburan.",
        en: "A warm gathering with the families, dinner, and entertainment.",
      },
    },
  ],

  /* ----- interface strings, Bahasa Indonesia first ------------------ */
  i18n: {
    id: {
      kicker: "Undangan Pernikahan",
      to: "Kepada Yth. Bapak/Ibu/Saudara/i",
      guestFallback: "Tamu Undangan",
      open: "Buka Undangan",
      weddingOf: "Pernikahan",
      heroAnd: "&",
      countdownTitle: "Menghitung Hari",
      cd: { d: "Hari", h: "Jam", m: "Menit", s: "Detik" },
      cdDone: "Hari ini!",
      openingKicker: "Atur Pambagyo",
      openingTitle: "Salam Pembuka",
      coupleKicker: "Temanten",
      coupleTitle: "Mempelai",
      coupleIntro: "Dua keluarga, satu doa. Perkenankan kami memperkenalkan kedua mempelai.",
      storyKicker: "Lampahan Katresnan",
      storyTitle: "Kisah Kami",
      eventKicker: "Titi Laksana",
      eventTitle: "Rangkaian Acara",
      agendaTitle: "Susunan Acara",
      dateLabelKey: "Hari & Tanggal",
      timeKey: "Pukul",
      placeKey: "Tempat",
      dressKey: "Busana",
      openMap: "Buka Peta",
      addCalendar: "Simpan ke Kalender",
      googleCalendar: "Google Calendar",
      galleryKicker: "Pasren",
      galleryTitle: "Galeri",
      turutKicker: "Kanthi Urmat",
      turutTitle: "Turut Mengundang",
      giftKicker: "Tanda Kasih",
      giftTitle: "Kado Buku",
      giftBtn: "Tanya Alamat Pengiriman",
      giftPrivacy: "Alamat pengiriman hanya kami bagikan melalui WhatsApp agar tetap terjaga.",
      streamKicker: "Saking Tebih",
      streamTitle: "Siaran Langsung",
      streamBody: "Bagi Bapak/Ibu/Saudara/i yang berhalangan hadir, silakan menyaksikan prosesi melalui tautan berikut.",
      rsvpKicker: "Konfirmasi",
      rsvpTitle: "Kehadiran",
      rsvpIntro: "Mohon konfirmasi kehadiran Anda sebelum hari acara.",
      formName: "Nama",
      formNamePh: "nama Anda",
      formAttend: "Kehadiran",
      attendYes: "Insya Allah, hadir",
      attendNo: "Mohon maaf, berhalangan",
      formGuests: "Jumlah Tamu",
      formNote: "Pesan (opsional)",
      formNotePh: "titip pesan untuk kami…",
      rsvpSend: "Kirim Konfirmasi",
      rsvpThanks: "Terima kasih! Konfirmasi Anda telah kami terima.",
      rsvpWa: "Kami membuka WhatsApp untuk mengirim konfirmasi Anda — silakan tekan kirim di sana.",
      rsvpMail: "Kami membuka aplikasi e-mail untuk mengirim konfirmasi Anda — silakan tekan kirim di sana.",
      rsvpFail: "Maaf, konfirmasi belum dapat terkirim. Mohon hubungi kami langsung melalui WhatsApp atau pesan pribadi.",
      wishKicker: "Sungkem & Donga",
      wishTitle: "Ucapan & Doa",
      wishName: "Nama",
      wishMsg: "Ucapan & doa",
      wishMsgPh: "doa terbaik untuk kedua mempelai…",
      wishSend: "Kirim Ucapan",
      wishEmpty: "Jadilah yang pertama mengirim doa.",
      wishLoading: "Memuat ucapan…",
      wishOffline: "(Ucapan langsung membutuhkan Firebase — lihat ../firebase.js)",
      wishFail: "Maaf, ucapan belum dapat terkirim. Silakan coba lagi.",
      wishSent: "Ucapan terkirim. Terima kasih!",
      footerThanks: "Merupakan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir.",
      nav: { home: "Beranda", acara: "Acara", galeri: "Galeri", rsvp: "RSVP", ucapan: "Ucapan" },
      icsName: "pernikahan-milena-kafka.ics",
    },
    en: {
      kicker: "Wedding Invitation",
      to: "Dear Mr/Mrs/Ms",
      guestFallback: "Honoured Guest",
      open: "Open Invitation",
      weddingOf: "The Wedding of",
      heroAnd: "&",
      countdownTitle: "Counting the Days",
      cd: { d: "Days", h: "Hours", m: "Mins", s: "Secs" },
      cdDone: "Today!",
      openingKicker: "Atur Pambagyo",
      openingTitle: "Words of Welcome",
      coupleKicker: "Temanten",
      coupleTitle: "The Couple",
      coupleIntro: "Two families, one prayer. Allow us to introduce the bride and groom.",
      storyKicker: "Lampahan Katresnan",
      storyTitle: "Our Story",
      eventKicker: "Titi Laksana",
      eventTitle: "The Events",
      agendaTitle: "Order of the Day",
      dateLabelKey: "Date",
      timeKey: "Time",
      placeKey: "Venue",
      dressKey: "Attire",
      openMap: "Open Map",
      addCalendar: "Save to Calendar",
      googleCalendar: "Google Calendar",
      galleryKicker: "Pasren",
      galleryTitle: "Gallery",
      turutKicker: "Kanthi Urmat",
      turutTitle: "Also Inviting",
      giftKicker: "Tanda Kasih",
      giftTitle: "A Book as a Gift",
      giftBtn: "Ask Shipping Address",
      giftPrivacy: "We only share the shipping address through WhatsApp so it stays private.",
      streamKicker: "Saking Tebih",
      streamTitle: "Live Streaming",
      streamBody: "If you are unable to attend in person, please join the ceremony through the link below.",
      rsvpKicker: "Reply",
      rsvpTitle: "RSVP",
      rsvpIntro: "Kindly confirm your attendance before the day.",
      formName: "Name",
      formNamePh: "your name",
      formAttend: "Attendance",
      attendYes: "Joyfully attending",
      attendNo: "Regretfully unable",
      formGuests: "Number of Guests",
      formNote: "Note (optional)",
      formNotePh: "a note for us…",
      rsvpSend: "Send RSVP",
      rsvpThanks: "Thank you! Your RSVP has been received.",
      rsvpWa: "We opened WhatsApp with your RSVP — please press send there.",
      rsvpMail: "We opened your e-mail app with your RSVP — please press send there.",
      rsvpFail: "Sorry, your RSVP could not be sent. Please contact us directly on WhatsApp or by message.",
      wishKicker: "Sungkem & Donga",
      wishTitle: "Wishes & Prayers",
      wishName: "Name",
      wishMsg: "Your wish or prayer",
      wishMsgPh: "your best prayer for the couple…",
      wishSend: "Send Wish",
      wishEmpty: "Be the first to leave a prayer.",
      wishLoading: "Loading wishes…",
      wishOffline: "(Live wishes need Firebase — see ../firebase.js)",
      wishFail: "Sorry, your wish could not be sent. Please try again.",
      wishSent: "Wish sent. Thank you!",
      footerThanks: "It would be our joy to have you with us on the day.",
      nav: { home: "Home", acara: "Events", galeri: "Gallery", rsvp: "RSVP", ucapan: "Wishes" },
      icsName: "milena-kafka-wedding.ics",
    },
  },
};
